### ISSUE TITLE
Increase Travis timeout on windows

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-messenger#118]
The windows build sometimes takes ages which causes travis to terminate it after 10 minutes because of no output generated.

Increase this to 30 minutes or something.

**Comment by sachaaaaa** [comment]
Reopening due to Windows builds still failing on Travis with "chromedriver did not start within 5000ms".
Potential solution:
https://github.com/electron/spectron/issues/144#issuecomment-404451340

**Comment by Mikunj** [comment]
Uhm that error has nothing to do with the travis timeout 🤔 
Travis timeout is when travis itself hasn't got any output from a command after X minutes, this is another issue.
