### ISSUE TITLE
libloki-protocol getting monolithic

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#123]
libloki-protocol.js is getting a bit cluttered with vaguely related functions that we just want to access globally through window.libloki

To make this stuff easier to find/maintain/etc we will split these into different categories (e.g. window.libloki.crypto or window.libloki.storage) and also group these into separate files to be grunted into libloki.js

**Comment by Mikunj** [comment]
```
libloki.crypto for FallBackSessionCipher and FallBackDecryptionError
libloki.storage forgetPreKeyBundleForContact, saveContactPreKeyBundle, removeContactPreKeyBundle
libloki.servicenodes for replenishSwarm
libloki.api for sendFriendRequestAccepted
```
