### ISSUE TITLE
New message notification toast is counting friend request accepted as a message

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#124]
### Bug description

The toast notification for receiving a new message will say you have one more message than you actually do if you haven't focused the window since receiving a friend request accepted message

### Steps to reproduce

1.  Send a friend request from A to B
2.  Minimise the messenger window on A
3.  Accept the friend request on B
4.  Send another message from B to A

Actual result:

A will receive a notification popup that will say "2 New Messages"

Expected result:

A should receive a notification popup that just shows the single new message

### Platform info

Operating System:

Linux

**Comment by Mikunj** [comment]
Signal collapses all notifications so that only the top most is shown. The unfortunate side effect of this is that we're unable to access previous notification data and thus we can't determine whether it was a friend accept or decline :(

**Comment by BeaudanBrown** [comment]
Hm where is it getting it's counter from tho?
Cause the little number above the conversation in the UI is correct?

**Comment by BeaudanBrown** [comment]
Kwl
Cause we still want the `Friend Request Accepted` notification, just not having the following notifications to count it :man_dancing:
