### ISSUE TITLE
Sending messages to your own pubkey fails

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-messenger#130]
I don't know the intended behaviour, like do we want to disable sending messages to ourselves?

Currently we can't send a friend request to yourself

**Comment by sachaaaaa** [comment]
Just tried allowing sending a friend request to ourself and the issue happens afterwards when a normal ciphertext is sent:
`Tried to decrypt on a sending chain`
My understanding is that in a normal session, Alice's sending ratchet matches Bob's receiving ratchet and vice versa, which isn't the case when sending to ourself.
I tried to hard-code to use the correct ratchet when decrypting, which gets past this error, but then I get a "Bad MAC" error. I'll attempt to swap the ephemeralKey when sending the message, before calculating the mac.

**Comment by sachaaaaa** [comment]
The Signal Desktop app doesn't provide this "feature" so we should simply add the messages to the conversation without actually sending them. Sending a message from the mobile app does appear as sent and received on mobile and received on desktop, but this is probably using the "sync" mechanism, which we will tackle later with multi-devices.

**Comment by BeaudanBrown** [comment]
Fixed
