### ISSUE TITLE
Enable P2P messaging ability over lokinet for messenger clients

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#140]
We have decided to run a HTTP server on each of the messenger clients which can receive messages with a similar API to the current storage server running on the nodes.

All lokinet instances have an ephemeral snapp when running which can be used to access the HTTP server if the server is bound to 0.0.0.0

Clients will use the regular Signal protocol (post friend request handshake) to share their .loki addresses to each other, and then make periodic POST requests to these addresses to maintain a list of which of their friends are online.

#### A and B establish a Signal protocol session together through the current friend request system
- This is a Pre-requisite for sending p2p messages

#### A starts the application
- use `localhost.loki` and `X.X.X.X.in-addr.arpa.loki` to aquire a list of `.loki` addresses that A can be contacted through.
- Broadcast a message (type: `p2p-address-broadcast`) to all of our friends via the Service Node (snode) Storage Server.
         This message should also contain A's `.loki` address.
    - The TTL of this message needs to be short (~1 hour or shorter)
 
#### A receives a `p2p-address-broadcast` message from B and does the following:
- Add B's loki address to our memory and mark B as online
- Send a `p2p-address-broadcast` message to **B's loki address** rather than a Service Node.
- Again this type of message always contains A's `.loki` address 
- B receives this message and adds A's loki address to memory and mark A as online

Whenever a contact is marked as online, we always send to their `.loki` address directly rather than a Service Node. We can also ignore the `pow` and `ttl` fields in the message.
 
## Flow of maintaining "online" status:
To check whether a contact is still online, we need to ping their `.loki` address to see if we get a response. 

We want to avoid the following when doing it:
- Only ping every X minutes as not to flood the other user
- Avoid both users pinging each other at the same time

We also have a timer which keeps track of when we were last contacted by the user. If a user doesn't contact us within that time frame then we mark them as offline.

We can infer is a user is online if they `POST` some data to our server, at which point we can reset the online timer.

The following is a use case:
- A receives a POST request to their HTTP server with B's `.loki` address + a signature from B
    - respond with 201 and starts a heartbeat timer
- B receives A's 201 response, marks A as "online" and starts their heartbeat timer
- B's timer completes and B sends a POST request to A with a signature

This process repeats until the contact is unreachable. At that point we set that contact to offline.

**Comment by sachaaaaa** [comment]
Closing as this feature as been implemented.
Any potential p2p bugs will be logged in new issues.
