### ISSUE TITLE
Allow deleting all data on password dialog.

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-messenger#146]
Currently if a user has set a password then the password dialog is shown at the start.

In the case that the user forgets this password, there is no way for them to completely reset their database other than manually navigating to the folder storing the info and deleting that.

I propose adding a button on the password dialog which allows the user to delete the db, starting completely from scratch.

Thoughts @sachaaaaa @BeaudanBrown @KeeJef

**Comment by KeeJef** [comment]
Yes, agree on this, although it should probably just be called create new account, and a dialog box should pop up warning the user that creating a new account will delete the old one
