### ISSUE TITLE
Create curlable link to download messenger toynet bootstrap.signed

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#149]
We have just been manually downloading the bootstrap.signed file from one of our toynet nodes and going from there when we want to join our messenger toynet

Since we will probably be wanting other people to start testing the messenger soon (and messaging each other) we should make it easier to set up lokinet properly to do so

We should create a simple script similar to the default lokinet-bootstrap command which downloads am identity file from our vps for a user to plop right in to their lokinet folder

How this is actually used is still up for debate
- Should the messenger itself try and "install" this file in the user's lokinet folder? (seems complicated)
- Should a simple script be in the root of the github?
- Should we just put a link to one of the identity files with instructions on the github?

**Comment by Mikunj** [comment]
We can use the already existing lokinet bootstrap and pass our vps endpoint instead
