### ISSUE TITLE
Retry send doesn't work

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#151]
# Bug description
Need to confirm if happens for both messages and friend requests.
When sending fails, clicking on Retry Send triggers a 
```
retrySend: Attempted to retry, but no numbers to send to!
```

# Steps to reproduce
1. disconnect from the internet or stop the localhost http storage server
2. Try to send a friend request
3. reconnect
4. click "Retry send"
5. Notice how nothing happens, check the logs for the error message

**Comment by Mikunj** [comment]
You have to make sure that any errors thrown are of the type `ReplayableError` and that you add its name to `isReplayableError(e)` in `message.js`

**Comment by Mikunj** [comment]
This seems to be a by-product of beau's changes. His new PR #147 should be fixing this.

**Comment by sachaaaaa** [comment]
Fixed in #147 indeed.
