### ISSUE TITLE
Mitigate spam attacks

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#184]
During discussions with the messenger team, we realised it would be currently pretty easy to create thousands of key pairs and spams users with thousands of friend requests.

So we need a way to prevent this.

There are solutions on the client side, using whitelists etc. but at the expense of a diminished user experience (if you get spammed and enable a whitelist feature, it will be more difficult for new contacts  to send you friend requests easily).

Other solutions would be to allow users to verify their pubkeys, for example by service nodes.

Something like
1. user creates an account, gets a pubkey
2. user asks multiple random service nodes to start verification
3. service nodes each send a riddle (CAPTCHA) that the user needs to manually answer (no automation possible here)
4. if the riddle is answered correctly, the service node signs the user's pubkey
5. Next time the user sends a friend request, it would send the verification proof with it, which is basically a list of signatures and corresponding service node pubkeys.
6. Anybody can then decrypt those signature and validate that they were provided by existing service nodes.

**Comment by KeeJef** [comment]
This is prevented by requiring a PoW for each friend request sent, there are probably better protections but using this as a simple solution for right now seems fine
