### ISSUE TITLE
Messenger only remembers the last most failed sent message

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-messenger#185]
### Bug Description

When you send messages to a person and they all fail, when you reload the messenger, only the last failed sent message remains.

### Steps to Reproduce

1.  go offline
2.  send multiple messages
3.  reload

Actual Result:

Only the last sent message stays

Expected Result:

All of the messages that errored should stay

**Comment by sachaaaaa** [comment]
I wasn't able to reproduce the issue at first glance.
Maybe there are other factors that trigger the bug?

**Comment by Mikunj** [comment]
This seemed to be an issue on my branch when i was testing attachments, it should be fixed in it locally. My bad
