### ISSUE TITLE
P2P does not recover after 1 failed message

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#192]
Currently we set a contact as offline as soon as we fail to send him 1 message via P2P.
Once marked as offline, we have no way to restore the P2P session unless one of the two participants restart their application, which would send a broadcast message.

When we are online, we currently only send a broadcast message (or ping) to our online contacts. Maybe we should attempt sending a ping to all contacts for which we have a .loki address stored in memory.

**Comment by Mikunj** [comment]
could we compare timestamps in the message received and if we see that it's within a certain time frame i.e 1 minute then we can mark that person as online and we send them the ping?

**Comment by BeaudanBrown** [comment]
We could but this would still require that someone messages someone before they will be marked online again
A naive approach I can think of is sending broadcast messages with tll of 1 minute to all your offline contacts over storage server every minute but feels pretty brute force?
