### ISSUE TITLE
Handle "wrong swarm" error code

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#204]
Due to the dynamic nature of swarms, the cached list of service nodes belonging to a recipient's pubkey might be stale or outdated.
If a client tries to store a message or retrieve his own messages to/from the wrong service node, the response should have a specific error code and eventually return the up-to-date list of service nodes, 
a la  "this is the list you're looking for".

**Comment by sachaaaaa** [comment]
HTTP error code 421 seems applicable:
> The 421 (Misdirected Request) status code indicates that the request
   was directed at a server that is not able to produce a response.
   This can be sent by a server that is not configured to produce
   responses for the combination of scheme and authority that are
   included in the request URI.

**Comment by BeaudanBrown** [comment]
Think I accidentally combined 2 PRs so this was solved by #258
