### ISSUE TITLE
Increase default window size

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#215]
On Windows 10 in the seed phrase screen the register button is cut off, this occurs at 1920 x 1080 screen resolution, we should increase the size of the window so the register button is visible. 

![image](https://user-images.githubusercontent.com/27277414/53466927-f8d26c00-3aa7-11e9-8f3b-5fcb62b96957.png)

**Comment by sachaaaaa** [comment]
This issue would probably be redundant once we have a nicer 2-step registration process as stated in #232
