### ISSUE TITLE
New Loki messenger icon

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#217]
The current icon should be replaced with a new icon, @joshalosh will work on this

**Comment by Mikunj** [comment]
🤔 didn't we already do this? or is it a different icon from the one we have now?

https://github.com/loki-project/loki-messenger/blob/development/images/icon_128.png

**Comment by Joshalosh** [comment]
I'll work on getting it updated

**Comment by KeeJef** [comment]
I don't think we will need to update this icon for now, should see some movements in the future
