### ISSUE TITLE
Pubkeys exchanged in conversations prevent freind requests

### ISSUE THREAD

**Issue by Haafingar** [loki-project/loki-messenger#221]
### Bug Description

![capture](https://user-images.githubusercontent.com/10295544/53532625-ac406c80-3b4b-11e9-8094-219181569707.PNG)

If a user exchanges someone elses pubkey via loki messenger, inputting that pubkey into the search bar prevents the user form being able to start a chat with that pubkey. Unless the message with the pubkey is deleted, the user cant get around this.

We should add a workaround method, or have the search bar detect when a pubkey is inputted such that it can offer the user to start a chat with that pubkey as well as past hits of it in messages.

**Comment by BeaudanBrown** [comment]
Actually after looking at this screenshot it seems that you actually *didn't* copy jeffs pubkey, you are actually searching for the pubkey of that convo
BUT this raises some other potential concerns
Did you mess up copying the pubkey sent to you or did the copy functionality fail?
Also I know you were messaging me and I had my nickname set but you aren't seeing it so we need to look into why that didn't work

**Comment by Haafingar** [comment]
I must have had your pubkey on the clipboard, and the copying failed when i tried to copy jeff's pubkey. This should be fixed to be more intuative
