### ISSUE TITLE
No right click menu for messages

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#222]
If someone tries to right click some highlighted text in a message to copy it nothing happens
Ctrl + C still works, however

I'm not sure if this is an intentional decision by signal upstream, but it could be confusing especially since sharing other user's pubkeys through the messenger is likely to be common

**Comment by sachaaaaa** [comment]
I think "copy/paste" should be there at least.
We don't want things like "view source" etc.

**Comment by BeaudanBrown** [comment]
Ah right that's probably why they disabled it
Would need to implement a whole custom right click menu I guess :-1:
