### ISSUE TITLE
Can't use mouse scroll to scroll conversation

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#228]
At least for me I can't use the scroll wheel to scroll through messages, not sure if this is also the case in signal upstream

**Comment by KeeJef** [comment]
i can use the scroll wheel fine

**Comment by BeaudanBrown** [comment]
Yeah ok just double checked and I can use the scroll wheel after restarting app, so something must have caused the scroll functionality to fail.
I will try investigate

**Comment by BeaudanBrown** [comment]
Pretty sure this is actually my mouse dying
