### ISSUE TITLE
Network status warning is buggy

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#230]
Network status shows as offline while I can see people online and can actually talk to them via p2p.

<img width="294" alt="screen shot 2019-02-28 at 2 43 28 pm" src="https://user-images.githubusercontent.com/40749766/53539891-74472280-3b67-11e9-8d17-ae9c3de1e804.png">

**Comment by BeaudanBrown** [comment]
Was that staying there permanently or would just appear and disappear?
Because I know that signal has this interface poll to check the status, it isn't reactive (like to events)

**Comment by sachaaaaa** [comment]
So I'm getting `NotFoundError: ENOTFOUND` and/or a timeout from the 2 snodes I'm retrieving my messages from.
But p2p is still working, since it doesn't need snodes to be working.

**Comment by BeaudanBrown** [comment]
Ah right, I wonder how we should handle this then because we can really have a spectrum of "connectivity" I guess (depending on which snodes you are able to connect to)

**Comment by sachaaaaa** [comment]
We could make more detailed warnings:
- all queries fail (snodes + p2p) and `!navigator.onLine` => "**Disconnected** Check your connection"
- can't reach snodes but p2p works and `navigator.onLine` => "**Connectivity Issues** You are connected to the Internet but not to the Loki Network"

**Comment by BeaudanBrown** [comment]
New connection model addresses this (all connections must fail before connectivity is set to offline)
