### ISSUE TITLE
Own nickname displayed is wrong

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#231]
Ther user nickname in the menu doesn't match the nickname that other people see, which is show in the edit window.
<img width="640" alt="screen shot 2019-02-28 at 2 47 54 pm" src="https://user-images.githubusercontent.com/40749766/53540027-f3d4f180-3b67-11e9-841a-8b572707e5e1.png">

**Comment by Mikunj** [comment]
hmm, could you describe the steps you took for this to occur?

**Comment by sachaaaaa** [comment]
From memory, I just set the nickname in the registration window then changed it inside the app, but that new nickname didn't get saved to the database nor was sent to the contacts.
Will try to reproduce, but if it doesn't happen again within a week I'll assume I did something fishy while the debugger was open.

**Comment by BeaudanBrown** [comment]
Closing until reproduced
