### ISSUE TITLE
DNS Resolution timeout Send failed 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#246]
When messenger cannot resolve a path to a single node in a swarm (currently related to https://github.com/loki-project/loki-network/issues/378 ) it shows the message status as failed. 

It may be the case in the future that when you send a message to a swarm you can tolerate the failure of say a single node out of 3 nodes, in this case the message should still show as sent, since the client will still be able to find the message on the 2 other nodes.

**Comment by BeaudanBrown** [comment]
This happens now, closing
