### ISSUE TITLE
Remove Signal prefix from pubkeys

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#250]
Signal pubKeys are prefixed with `05` for versioning purposes, making them 33 bytes keys.
We should either keep that prefix internal to the Messenger and remove the `05` before making requests with the external world, or remove the `05` altogether even internally.
I would try removing the `05` altogether to prevent repeatedly having to clean the pubkeys at different locations in the code.

**Comment by neuroscr** [comment]
You should leave some type of versioning mechanism in place.
The less matter is the compatibility.

**Comment by sachaaaaa** [comment]
I have changed my mind about the prefix thing, based on your suggestions.
I think we should embrace the whole prefix stuff and keep using `05` in the messenger.
Instead, have the storage server read the prefix and map it to a known Curve/scheme (e.g. if prefix is `05`, expect 32 bytes afterwards and treat it as a Curve25519 pubkey).
