### ISSUE TITLE
Can't build release

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#265]
Running `yarn build-release` results in this output for me, not sure if I'm the only one?
`image /home/beaudan/workspace/loki-messenger/build/icon.ico must be at least 256x256`
I have checked and this file *is* there and *does* say it is 256x256

**Comment by sachaaaaa** [comment]
Can't reproduce on osx.
Gitlab is also not having issues with building release binaries.

**Comment by BeaudanBrown** [comment]
My fault
