### ISSUE TITLE
getOurSwarmNodes() Fails on macOS

### ISSUE THREAD

**Issue by nielsandriesse** [loki-project/loki-messenger#275]
Running latest loki-network master with latest loki-messenger development. Seeing ~4 snodes under ~/.lokinet/netdb. Running `nslookup random.snode` looks fine. However, doing `nslookup snode-address-printed-above 127.0.0.1` gives an `NXDOMAIN` error. Running Loki Messenger doesn't work because hitting http://snode-address-returned-by-getRandomSnodeAddress():8080 with `method = "get_snodes_for_pubkey"` and `params = { pubKey : "..." }` gives an `ENOTFOUND` error. Not entirely sure if this is a Loki Messenger problem or a Loki Network problem.

**Comment by BeaudanBrown** [comment]
Assuming Lokinet issue until confirmed otherwise
