### ISSUE TITLE
UX Improvement - Introduce new Status Bar and new Icons

### ISSUE THREAD

**Issue by Haafingar** [loki-project/loki-messenger#287]
Using the Loki messenger is going to be a somewhat frustrating experience if we don't give the user some idea about why the messenger is being slow or what is going wrong when inevitably something does. 

I propose we add a persistent status bar just above the text input box that will keep the user informed about the current status of the conversation. 

I have made a really crap illustration to show off what I'm talking about:

![MarvelousIllustration](https://user-images.githubusercontent.com/10295544/58152858-f7809c00-7cb0-11e9-97e4-c5560980f796.jpg)

This status bar should display the following:

- Connected to peer, ready to send (GREEN) when synchronous messaging mode is on
- Ready to send offline message (GREY) when async mode is on.
- Calculating Proof of Work, Estimated x Seconds (BLACK) when PoW is being done
- Connecting to Swarm (DARK GREEN) when https request to snode is being made
- Delivered to Swarm (GREEN) after post is confirmed
- Not connected to Lokinet (ORANGE)
- Unable to poll Swarm (RED)
- Message sending failed, reason (RED)

The current message being processed should also have a three tier icon system, displaying a spinning cog, spinning network icon, and finally a single hollow tick which becomes a solid tick when posting is complete.

Each icon should be greyed out when the process starts. As each step initiated, the icon becomes dark grey and starts spinning (if appropriate). As each step is completed it turns green, except the posted tick. When a read receipt is delivered, the solid tick becomes a solid double tick and turns green.

If messages were delivered synchronously, display the P2P icon in place of the PoW and connection signs. 

Once the message is buried to beyond the last batch of messages, do not display these icons. 

I will add to this once the first lot of this has been put in.

**Comment by BeaudanBrown** [comment]
Reminder for tomorrow
First thing that comes to mind after looking at this is that sending multiple messages in a row could potentially look weird with the cog etc appearing below the message bubble, since after each messages completes sending the cog etc will disappear and have to shift the position of all the messages below it
