### ISSUE TITLE
Note to self broken

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#293]
**Describe the bug**
Probably from the most recent signal merges, now you can do a "Note to self" if you send a message to your own pubkey
But something is broken with the friend request system for us

**To Reproduce**
1. Start fresh client
2. Copy your own pubkey into the search box
3. Click note to self
4. Send message to yourself
5. Can't send any more cause it thinks you are waiting for a friend request response

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/43770694/58610751-fd4d3180-82ef-11e9-9318-3808a0350647.png)

**Comment by Mikunj** [comment]
We should make it so we are automatically friends with ourself

**Comment by BeaudanBrown** [comment]
Fixed by #307
