### ISSUE TITLE
Remove "View all Media" section from the drop down menu.

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/loki-messenger#301]
Remove "View all Media" section from the drop down menu when in a chat with someone.

We don't have the integration to send media yet so remove the option to view sent media.

**Screenshots or Logs**
![view all media](https://user-images.githubusercontent.com/39609800/59400428-b9235c00-8dda-11e9-8acf-60d24703244b.JPG)

**Other information (please complete the following information):**

* Device: PC
* OS: ALL

**Comment by BeaudanBrown** [comment]
Fixed by #306
