### ISSUE TITLE
One way p2p doesn't work

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#304]
We need to decide how we want to handle uni directional p2p, because there will likely be many users who aren't able to punch upnp holes etc but we should probably still allow them to *send* p2p messages

Will require some thinking, maybe a default broadcast message to test p2p connection while letting the other person know you can't be reached p2p

**Comment by sachaaaaa** [comment]
#317 should add support for "one way p2p"

**Comment by sachaaaaa** [comment]
Assuming #317 fixes this issue.
