### ISSUE TITLE
Add an `import from clipboard` button

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#318]
It's kind of weird to have to past someone's pubkey into the search field to start a new conversation
We should also add a button to start a conversation with the pubkey in the clipboard

**Comment by msgmaxim** [comment]
May not be what we wanted exactly (not sure how the interface would look like with the import button), but I've added a button to paste from clipboard if the pubkey is valid (#370)

**Comment by BeaudanBrown** [comment]
Closed by #370
