### ISSUE TITLE
Release notes link is broken- 404

### ISSUE THREAD

**Issue by OlderNews** [loki-project/loki-messenger#335]
Hey there, using the Loki Messenger Beta for Windows V1.0.0-beta1.

When you click the help tab> Release notes. It directs you to a broken link- https://github.com/loki-project/loki-messenger/releases/tag/v1.0.0-beta1

Please swap the broken link to a working link, so I can check all those sweet, sweet release notes.

**Comment by BeaudanBrown** [comment]
Whoops... PR up
