### ISSUE TITLE
Allow for the selection of multiple messages

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#400]
Mobile and desktop should allow for the selection of multiple messages, on mobile this should be done using a long press with a small tick box beside each message that you want to select 

![photo6235509958322006200](https://user-images.githubusercontent.com/27277414/62849347-a964bd00-bd22-11e9-9790-6e14f8e5cd3a.jpg)

On desktop this could be done by detecting when a user clicks directly on the text box instead of highlighting the actual text inside, if you want an example, look at telegram web since i think their way of selecting multiple messages is pretty slick

After selecting multiple messages you should be able to delete those messages as a group (if they are yours or you are an admin in a group chat/ chat channel) Or you should be able to forward those messages to another chat.

**Comment by KeeJef** [comment]
related to #505

**Comment by msgmaxim** [comment]
Done in #592
