### ISSUE TITLE
Local Link previews including GIFS 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#406]
Links to a select popular websites like, Youtube, Imgur, Reddit, Instagram should be locally rendered to show a preview of the content they link to. Signal already has this on desktop and mobile it just needs to be fixed in Loki messenger

**Comment by KeeJef** [comment]
We should also support rendering GIFs from GIPHY and Tenor, as these are commonly used in GIF keyboards

**Comment by sachaaaaa** [comment]
Can you remember if the bug was affecting link previews when the link was in the text editor but before the message was sent, and/or when sending/receiving a message?
From a first glance it looks like changes from upstream were badly merged into our repo.

**Comment by sachaaaaa** [comment]
Just making sure, have you enabled this feature in the settings first? It's disabled by default.

**Comment by sachaaaaa** [comment]
The bug was fixed in #362 and should be in our 1.0.0-beta3 version.
We definitely can add more urls in the whitelist, like giphy and tenor. I think some imgur subdomain like `i.imgur.com` should also be added.

**Comment by sachaaaaa** [comment]
Also, worth noting the existing Signal functionality: 

Even if link preview is enabled in the global settings, it is be temporarily disabled per-conversation after the user manually closed the preview by clicking on the grey cross. After that, the link preview is disabled for this conversation even if a new url is entered, until the text editor is cleared of any characters.

**Comment by KeeJef** [comment]
@sachaaaaa Can we whitelist tenor.com and gph.is and giphy.com then i will close this

**Comment by KeeJef** [comment]
This will still need to be fixed in iOS and Android
