### ISSUE TITLE
Analytics collection

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#419]
We are going to need to start collecting essential reports about how users, use Loki messenger, this includes crash reports, logs, and usage stats, its important that we also do this in an ethical way that does not deanonymize users. 

I will update this issue shortly with a public post which details how we intend to do this

**Comment by KeeJef** [comment]
This is now completed on iOS and Android, using Mixpanel for UI interactions, and Crashlytics for crash reports i believe @neuroscr volunteered to implement similar collection on desktop.

**Comment by neuroscr** [comment]
for the record I didn't volunteer ;)

addressed in #512
