### ISSUE TITLE
Check permissions and reflect UI (Moderator Tags)

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-messenger#442]
Once a new endpoint has been added to the overlay to check if our key has mod permissions, we should check this on app launch and possibly periodically to update the UI to reflect our new status

**Comment by KeeJef** [comment]
A little sheriffs badge which intersects their avatar on the bottom left of the avatar would look cool.

**Comment by neuroscr** [comment]
I'm not sure we should give status publicly to moderators, or at least make it a configureable option. However we clearly need something to indicate you have moderator status to yourself.

**Comment by KeeJef** [comment]
Moderators should be publicly identifiable as they are in other applications, it increases accountability and makes the trusted members in the chat clear
