### ISSUE TITLE
Simplify profile/nickname update logic

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#450]
Currently there are
- `storage.setProfileName('John Smith')`
- `conversation.setProfile({ displayName: 'John Smith'})` (also seen `{profileName: '...'}`)
- `conversation.setProfileName('John Smith')`

So we need to simplify and remove redundancy.
It would be good that when updating our own profile name, only 1 call is needed (e.g. to profileController.setProfileName` and that conversationController would be listening to events related to profile updates (any of our contacts' profile + our own).

**Comment by Mikunj** [comment]
I feel the field names inside `conversation.js` are also a bit confusing in the case of determining differences between `profile`, `profileName` and `nickName/displayName`. I really think we can simplify this down into 1 variable which updates as users change their profiles or we update their nicknames.
