### ISSUE TITLE
Hide stale menu options for public chats

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-messenger#469]
**Describe the bug**
Some of the conversation options should be hidden for public chats.
The in-conversation menu shows the following stale options:
- Disappearing messages
- Show members (shows empty list?)
- Change nickname
- Copy public key (unless we want to let people manage public chats?)

Right-click on the conversation in the left-hand menu shows:
- Change nickname
- Copy public key

**To Reproduce**
- Open public chat and click on the right-hand side cog
- OR right-click on the public chat in the conversation and friend lists
- Notice the different options that are not relevant to public chat

**Screenshots or Logs**
![Screen Shot 2019-09-03 at 10 47 12 am](https://user-images.githubusercontent.com/40749766/64136975-8cf70480-ce38-11e9-9062-6d0caca5b9f3.png)
![Screen Shot 2019-09-03 at 10 47 25 am](https://user-images.githubusercontent.com/40749766/64136979-8f595e80-ce38-11e9-899d-ac5e92de6cb6.png)

**Other information (please complete the following information):**
Desktop 1.0.0-beta4

**Comment by KeeJef** [comment]
#474
