### ISSUE TITLE
Shouldn't be able to enable the component for typing new messages in news groups (should it be removed altogether?)

### ISSUE THREAD

**Issue by msgmaxim** [loki-project/loki-messenger#476]
**Describe the bug**

By default typing is disabled in loki news/updates groups. However, trying to respond to any of the existing messages enables typing and gives the user the ability to "send" messages (As far as I can tell, the messages don't leave the user's device)

**To Reproduce**

Go to Lokinetwork.news group and reply to any of the news items. From now on I can type and "send" messages.

**Screenshots or Logs**

![Screen Shot 2019-09-04 at 12 17 01 pm](https://user-images.githubusercontent.com/2591783/64221017-af5b5180-cf0e-11e9-843b-44d10063007d.png)

![Screen Shot 2019-09-04 at 12 25 02 pm](https://user-images.githubusercontent.com/2591783/64221115-124ce880-cf0f-11e9-9590-8297d16a7ea3.png)

**Comment by Mikunj** [comment]
Maybe we should just not render the typing bar at all?
