### ISSUE TITLE
Multiple message deletion

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#505]
Right now each message mus be deleted individually, this can be a pain for moderators trying to delete a lot of messages at once. we should enable a feature to batch delete messages by selecting and then deleting.

This issue should be implemented for Public chats and Person to Person chats

**Comment by neuroscr** [comment]
well I can do at least the backend, so I'll assign it to myself until that's done

**Comment by msgmaxim** [comment]
Done in #592
