### ISSUE TITLE
Implement Rate(?) Limit in Group Messaging to Prevent Spam

### ISSUE THREAD

**Issue by Skelaton4** [loki-project/loki-messenger#577]
**Describe the bug**
At the moment it is possible to spam the Loki Public chat with unlimited messages in a rapid succession. This leaves the group open to bots or users spamming the channels with messages. 

**To Reproduce**
Rapid messaging. 

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.
![image](https://user-images.githubusercontent.com/28955674/67525812-78d5c380-f681-11e9-892b-cbb69300390a.png)

**Other information (please complete the following information):**

* Device: Samsung S9+
* OS: Android
* Loki messenger Version or Git commit hash: 1.30

**Comment by KeeJef** [comment]
Closed for #585
