### ISSUE TITLE
Public Chat: Quoting "Original message not found"

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-messenger#647]
**Describe the bug**
Quoted messages sometimes aren't found

**To Reproduce**
Have some one quote a message from a while ago.

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: All
* OS: All
* Loki messenger Version or Git commit hash: 1.5

**Comment by msgmaxim** [comment]
#651 addresses this problem on Desktop
