### ISSUE TITLE
Push Notifications - APL 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#675]
Apple allows users to receive push notifications, however it does so using a centralized system, where a developer must hold a special singing key to contact the Apple push notification server, at which point the server sends a push notification to the device. 

Push notifications when a user receives a message are essential so we want to support this as a feature, however we want to maintain maximum privacy for the users who use this service. This is how i'm proposing it will work. 

The Loki team will need to run a centralized server that can scan swarms for incoming messages and sign push notifications. This needs to be centralized, since apple requires the developer have signing keys and sign each push notification, the keys to sign a push notifications cannot be properly distributed to Service Nodes without risking a malicious Service Node spamming users with push notifications. 

It will work like this

1. The User registers their device + Loki messenger application with APNS (Apple push notification service), APNS gives the device a token. 
2. The User registers that token + their long term public key with the Loki Centralized server 
3. The Loki centralized server scans the public keys swarm for new incoming messages, when it sees an incoming message for the user it sends a signed push notification to APNS 
4. APNS provides that push notification to the user.
5. The Device sees the push notification and checks its swarm for any incoming messages, which it downloads, decrypts and displays to the user through a Local notification

This is the basic process, however we want to shield Apple from knowing when a device has received a message using Loki messenger. To do this we want to send a number of dummy push notifications every X period. To do this we will need to encrypt each push notification for the long term public key of the device and tag it as a dummy push or a real push. When the push notification is decrypted  by the device the device will read this tag and only act to retrieve the message if it is tagged as a real request. 

Push Notifications will be optional for all iOS users as they do degrade privacy, specifically the centralized Loki server will know the mapping between your APNS token and your public key.

**Comment by neuroscr** [comment]
I think this could live in the file server.

**Comment by KeeJef** [comment]
Implemented here https://github.com/loki-project/loki-messenger-ios/pull/72 Server side code is unpublished

**Comment by KeeJef** [comment]
This is now implemented slightly differently 

When a device is registers with the centralized Loki push notification server the client sends only their APNS token to the server

The Loki centralized push notification server then sends a push notification to Apples servers at a constant interval, these are forwarded to the Apple device which wakes silently in the background and checks its storage server for new messages, if new messages are found it renders those messages as a local notification to the user, if no new messages are found the device does not display a notification to the user.

The advantage here is that the Loki centralized server has no idea what your public key is, or when you receive messages. The Loki centralized server only knows that a device with APNS id at one point was registered with it. And apple doesnt know your public key or when you receive a message either.
