### ISSUE TITLE
Text Secure group notification in Public chat 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger#694]
**Describe the bug**
when using the Loki public chat on Android a notification in the group pops up saying something like "Youve accepted textsecure group !PUBLIC KEY Friend request"

**To Reproduce**

Seems to be happening randomly, not sure what caused it but it does seem to show quite regularly so should be reproducible 

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

![image](https://user-images.githubusercontent.com/27277414/70692169-dfd13980-1d0e-11ea-9306-df2616a6379b.png)

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac] Android 
* OS: [e.g. Ubuntu 16.04, Windows 10] Android 9 
* Loki messenger Version or Git commit hash: 1.5.2

**Comment by Mikunj** [comment]
This should be fixed in the next release
