### ISSUE TITLE
Loki Messenger desktop unresponsive after being open for some time.

### ISSUE THREAD

**Issue by Joshalosh** [loki-project/loki-messenger#704]
**Describe the bug**
After having the desktop application open for a while, the app window goes completely white and becomes unresponsive.

**To Reproduce**
Leave it open on my computer for a while

**Screenshots or Logs**
<img width="1063" alt="Screen Shot 2019-12-17 at 11 57 48 am" src="https://user-images.githubusercontent.com/13159770/70955315-7a8d9780-20c4-11ea-834f-4f04d9198071.png">

**Other information (please complete the following information):**

* Device: Mac
* OS: macOS Catalina, Version 10.15.1
* Loki messenger Version 1.0.0-beta7

**Comment by KeeJef** [comment]
Update to the newest version, this bug has been fixed
