### ISSUE TITLE
Where to start with contributing?

### ISSUE THREAD

**Issue by liilac** [loki-project/loki-messenger#80]
Hi,

I'm a lokinet contributor and was having a look at this repo but I don't see any issues nor mentions of where discussion typically takes place, etc.

Is anyone able to give me some pointers on this?  I'd like to contribute to the messenger.

**Comment by KeeJef** [comment]
Right now we have an internal issues spreadsheet which we are working on, over the coming weeks we will try to intergrate this with github projects, or we will just make all of those tasks into issues which can be worked on by outside contributors @sachaaaaa which ever of these options you think would be the best we should move forward with

**Comment by liilac** [comment]
If it helps, I have access to the lokinet spreadsheet.  I don't recall whether loki messenger stuff is on the same workbook or not, have to check.

**Comment by KeeJef** [comment]
We have added a public project board here https://github.com/loki-project/loki-messenger/projects/1
